### ISSUE TITLE
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

### ISSUE THREAD

**Issue by amotl** [bebleo/smtpdfix#195]
Dear James,

first things first: Thanks a stack for conceiving and maintaining this excellent package. It is tremendously helpful for conducting full system tests.

We are currently in the process of giving some love to an abandoned Python project over at [1,2], where we would like to use `smtpdfix` to verify email delivery within the test harness.

When starting with `smtpdfix`, we quickly ran into #89. However, we were happy to find #95, which already removed that feature. Other than the potential hiccup for some users where `socket.gethostbyname()` croaks, we believe it will be a great enhancement because the service will be available for consumption instantly, without going through key material and certificate generation, right?

So, we already recognized you were preparing version 0.4.0, at #144. May we humbly ask if you could publish version 0.4.0 to PyPI to make it available for pulling it into downstream projects? We think it would be a great benefit for the community. Please let us know if there are some blockers where we may be able to help out.

With kind regards,
Andreas.

[1] https://github.com/isarengineering/SecPi
[2] https://github.com/SecPi/SecPi/issues/120

---

**Describe the bug**
When the library is initializing, it croaks like:
```python
        # Generate public certificate
        hostname = socket.gethostname()
>       ip = socket.gethostbyname(hostname)
E       socket.gaierror: [Errno 8] nodename nor servname provided, or not known

.venv/lib/python3.10/site-packages/smtpdfix/certs.py:35: gaierror
```

**To Reproduce**
It happens on slightly misconfigured systems where the designated hostname does not resolve to an IP address.
```python
>>> import socket
>>> socket.gethostbyname(socket.gethostname())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```

**Expected behavior**
The library should work instantly by starting an SMTP server on port 8025.

**Environment (please complete the following information):**
 - macOS 10.15.7
 - Python 3.10
 - smtpdfix 0.3.3

**Comment by bebleo** [comment]
Hi Andreas,

Thanks for contributing this bug report.

Unfortunately I don't think #95 will resolve this bug because it removes `generate_certs` from the public API, but the code is still present in `_generate_certs` which replaced it.

I'll try to put some work into this in the next couple of days.

**Comment by amotl** [comment]
Dear James,

thank you very much for the prompt improvement and the subsequent release. We can confirm the library is working without errors now, even on a misconfigured system.

However, we observed that a test case usually taking 0.43s on a properly configured system now only completes in 20.50s. While it is running, several stalls occur, indicating that the lack of the resolvable host name has some further drawbacks down the line while running the SMTP conversation.

So, with this insight, correct local hostname -> IP address resolution should be mandatory before doing any SMTP communication at all, either with a real server, or with this library. It may make sense to mention that detail within the README or another FAQ/troubleshooting section of the documentation, and maybe even drop a word in the corresponding error log message about it.

In any case, we wanted to share our observations with you and the community.

Thank you again and with kind regards,
Andreas.

**Comment by bebleo** [comment]
Dear Andreas,

Thanks for taking the time to report the performance issues. I've opened another issue, #198, to look into this further.

Would you be willing to share the test that produced the result on the new issue? Or could your point me to where I could read through the code?

I'd like to examine whether there is a way to resolve this -- unfortunately, my first thought is that it probably cannot be easily solved -- or if, as you suggest, warning users is the most practical approach.
