### ISSUE TITLE
load_dotenv() should not be executed inside the library

### ISSUE THREAD

**Issue by e-belair** [bebleo/smtpdfix#274]
load_dotenv() should not be executed on library loading
([see here](https://github.com/bebleo/smtpdfix/blob/198ad265fb61641a50aee5ccdbf47c2311585afd/smtpdfix/configuration.py#L11) ) because its loads the default .env file that we have inside our project.
If we need to load a specific .env file for testing, we are obliged to override all the values. It also can be a security issue.

I would recommend letting the user loading env file and then uses os.getenv() with default values.

**Comment by bebleo** [comment]
Bonjour Emmanuel,

Veuillez accepter mes excuses pour ma réponse tardif.

I will add this to the next milestone so that it’s corrected in the next major release.

Thanks for taking the time to report the issue. 🙂

**Comment by e-belair** [comment]
Hi! Sorry for late reply, I forgot to check my github notifications ....  
Thanks for the commit, I appreciate and I'll update my code asap! :-)
