### ISSUE TITLE
pip creates a `tests/` folder in site-packages and clashes with my test namespace.

### ISSUE THREAD

**Issue by thedamnedrhino** [bebleo/smtpdfix#328]
**Describe the bug**
When I install this package using `pip` on a `venv` environment (i.e. virtual environment created with `python -m venv .venv`), 
I get a folder called `tests/` folder directly in my `site-packages/` with files including `test-smtpdfix` and `test-smtp` and it clashes with my own `tests` package. I delete that folder and this fixes the issue.
**To Reproduce**
- `python -m venv .venv`
- `python -m pip install smtpdfix`
- look in `.venv/lib/python<version>/site-packages` and there is a `tests` folder.

**Expected behavior**
Are you adding tests in a root `tests` namespace on purpose?

**Environment (please complete the following information):**
 - OS: MacOS 12.6.3
 - Version: Python 3.10.0

**Comment by bebleo** [comment]
Thanks @thedamnedrhino for taking the time to report this issue. A release including a fix will be released soon.
