### ISSUE TITLE
README references SMTPD_SSL_CERTS_PATH which was removed in 0.5.2

### ISSUE THREAD

**Issue by holly-evans** [bebleo/smtpdfix#392]
**Describe the bug**
The README is inaccurate. SMTPD_SSL_CERTS_PATH no longer exists in 0.5.2

**To Reproduce**
Read the readme

**Expected behavior**
The README accurately describes how to config certs

**Environment (please complete the following information):**
 - OS: N/A
 - Version N/a

**Additional context**

**Comment by bebleo** [comment]
@holly-evans, Thanks for taking the time to report this issue. A correction will be on the main branch shortly and then included as part of version 0.5.3 once released.
